import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-black antialiased text-white">
        <Navbar />
        {children}
        <footer className="py-10 border-t border-zinc-900 text-center">
          <p className="text-zinc-600 text-sm">
            © {new Date().getFullYear()} DYOAGENCY. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
